services:
  - type: worker
    name: osint-bot
    env: docker
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: SHARED_SECRET
        sync: false
      - key: ADMIN_ID
        sync: false
