services:
  - type: worker
    name: osint-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: SHARED_SECRET
        sync: false
      - key: ADMIN_ID
        sync: false
